### ISSUE TITLE
Cost effectiveness vs Laravel Horizon in ECS

### ISSUE THREAD

**Issue by renanwilliam** [lukewaite/laravel-queue-aws-batch#32]
Hi @lukewaite ,

We run a queue/batch intensive application that is running in ECS Cluster in a distributed scenario (we have some dozens of workers running in parallel waiting new jobs with high sensitive auto-scaling configured).

Probably you have a similar scenario to create this package. I would like to check if you have compared AWS Batch costs vs a tradicional approach deploying containers running with Laravel Horizon.

Do you have measured something like that?

**Comment by antoniofigueiredotamura** [comment]
The package itself was not designed to do what Laravel Horizon does. Laravel Horizon is a monitoring tool.
